Feat/discover page
d-reader-organization/genesis-web pull request #65
Opened 2024-11-19 18:41 UTC by khubak

TODO: 

* fix grid misusage
* utilize usememo hook

2024-11-20 09:11 UTC, d-reader-josip requested changes

2024-11-20 09:11 UTC, d-reader-josip commented on src/models/genre-new/index.ts
remove `genre-new`

2024-11-21 08:28 UTC, khubak commented on src/app/(authenticated)/discover/comics/page.tsx
> +      <ComicsContent />
thoughts on custom ComicsContent component with slider/grid/row types?

2024-11-25 12:50 UTC, khubak commented on src/components/discover/ComicIssuesContent.tsx
> +        </Link>
will do once figma for all the cards is ready

2024-11-26 09:59 UTC, d-reader-josip requested changes

2024-11-26 09:59 UTC, d-reader-josip commented on src/api/genre/queries/useFetchGenres.ts
delete this

2024-11-26 09:59 UTC, d-reader-josip commented on src/app/(authenticated)/discover/creators/page.tsx
> +export default function DiscoverComicsPage() {
DiscoverCreatorsPage

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/ComicGrid.tsx
> +  const comicParams = useMemo(() => storeComicParams, [storeComicParams])
This is unnecessary

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/ComicGrid.tsx
> +          </Link>
This should be a Comic component

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/ComicGrid.tsx
> +              alt={comic.title + ' Cover'}
put alt as empty string

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/ComicIssueGrid.tsx
> +  const comicIssueParams = useMemo(() => storeComicIssueParams, [storeComicIssueParams])
remove this useMemo

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/DiscoverPageWrapper.tsx
> +export const DiscoverWrapper: React.FC<Props> = async ({ children, mainClassName }) => {
Rename to DiscoverPageWrapper

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/DiscoverPageWrapper.tsx
> +            <Tabs label={'Discover'} tabs={DISCOVER_PAGE_TABS} />
remove "{" and "}" brackets

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/discover/ShowMoreButton.tsx
Ask Matan to  add a "show more" button and explain the infinite scroll behavior

2024-11-26 09:59 UTC, d-reader-josip commented on src/components/shared/Tabs.tsx
> +        className='absolute -top-6 left-2 text-grey-100 text-transparent uppercase bg-gradient-to-b from-grey-400 via-grey-600 via-60% to-transparent bg-clip-text'
Switch from absolute to flex (with negative margin-top on the component below)

2024-11-26 09:59 UTC, d-reader-josip commented on src/constants/tabs.ts
> +    url: '/discover/comics',
use `RoutePath.DiscoverComics`

2024-11-26 09:59 UTC, d-reader-josip commented on src/providers/DiscoverFilterStoreProvider.tsx
> +  }
I don't think this catch is necessary tbh?

2024-11-26 09:59 UTC, d-reader-josip commented on src/providers/DiscoverFilterStoreProvider.tsx
> +    const completeGenresList = await fetchGenres({})
remove empty {} from `fetchGenres({})`

2024-11-26 09:59 UTC, d-reader-josip commented on src/app/lib/api/genre/queries.ts
> +export const fetchGenres = async (params: GenreParams): Promise<Genre[]> => {
make params optional `(params?: GenreParams)`

2024-11-29 13:30 UTC, merged